builders:
  build_ffi_generator:
    import: 'package:build_ffi_generator/builder.dart'
    builder_factories: ['create']
    build_extensions: {'.ffi.txt': ['.ffi.dart']}
    auto_apply: dependents
    build_to: source

targets:
  $default:
    builders:
      build_ffi_generator:
        enabled: true