name: build_ffi_generator
description: Builder to generate ffi bindings from a textual description
publish_to: none
version: 0.1.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  build: ^1.3.0
  dart_style: ^1.3.6
  meta: ^1.1.8
  charcode: ^1.1.3
  source_span: ^1.7.0

dev_dependencies:
  pedantic: ^1.8.0
  build_runner: ^1.10.0
  test: ^1.6.0